{{- if and ( eq .Values.spring.config.type "file") (hasKey .Values.spring.config "content") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helloworld.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "helloworld.name" . }}
    chart: {{ include "helloworld.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yml:
    {{ toYaml .Values.spring.config.content | indent 4  }}
{{- end }}